version: '3'
services:
  elasticsearch-service:
    build: elastic
    container_name: elasticsearch-service
    volumes:
      - ./elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
    environment:
      node.name: elasticsearch
#      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: 123456
      discovery.type: single-node
  mysql-service:
    build: db
    container_name: mysql-service
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: manager
    ports:
      - 3306:3306
  manager-service:
    build: manager-service
    container_name: manager-service
    restart: always
    ports:
      - 8090:8090
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/manager?useUnicode=true&characterEncoding=utf8
      SPRING_ELASTIC_URL: elasticsearch-service:9200

  question-service:
    build: question-service
    container_name: question-service
    restart: always
    ports:
      - 8091:8091
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/manager?useUnicode=true&characterEncoding=utf8
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
      args:
        NPM_MODE: test
    container_name: manager-front-service
    restart: always
    ports:
      - 8080:8080
  question:
    build:
      context: ./question
      dockerfile: Dockerfile
      args:
        NPM_MODE: test
    container_name: question-front-service
    restart: always
    ports:
      - 8081:8081


