server:
  servlet:
    context-path: "/manage"
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: cp-19930904
#    password: 1234qwer
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.jenschen.dao: debug