server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapper-locations: classpath*:mapper/*.xml
      default-enum-type-handler: com.jenschen.typehandler.ValueEnumTypeHandler
logging:
  level:
    com.jenschen.mapper: debug
