server:
  port: 8091
spring:
  security:
    prefix: lowcodeplatform
    defaultPassword: 123456
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  elasticsearch:
    uris: 192.168.221.128:9200
    password: 123456
    username: elastic
mybatis-plus:
  type-handlers-package: com.jenschen.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*.xml
    default-enum-type-handler: com.jenschen.typehandler.ValueEnumTypeHandler
logging:
  level:
    com.jenschen.mapper: debug

