server:
  port: 8200
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: manager-service
#          uri: http://127.0.0.1:8090
          uri: lb://MANAGER-SYSTEM
          predicates:
            - Path=/manage/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true